USE [master]
GO
/****** Object:  Database [Lunar]    Script Date: 3/05/2023 1:49:06 PM ******/
CREATE DATABASE [Lunar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lunar', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Lunar.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lunar_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Lunar_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Lunar] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lunar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Lunar] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Lunar] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Lunar] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Lunar] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Lunar] SET ARITHABORT OFF 
GO
ALTER DATABASE [Lunar] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Lunar] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Lunar] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Lunar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Lunar] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Lunar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Lunar] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Lunar] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Lunar] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Lunar] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Lunar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Lunar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Lunar] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Lunar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Lunar] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Lunar] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Lunar] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Lunar] SET RECOVERY FULL 
GO
ALTER DATABASE [Lunar] SET  MULTI_USER 
GO
ALTER DATABASE [Lunar] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Lunar] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Lunar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Lunar] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Lunar] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Lunar] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Lunar', N'ON'
GO
ALTER DATABASE [Lunar] SET QUERY_STORE = OFF
GO
USE [Lunar]
GO
/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 3/05/2023 1:49:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__MigrationHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ContextKey] [nvarchar](300) NOT NULL,
	[Model] [varbinary](max) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC,
	[ContextKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[comforts]    Script Date: 3/05/2023 1:49:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[comforts](
	[trigger_id] [int] IDENTITY(1,1) NOT NULL,
	[trigger_name] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[trigger_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EndUser]    Script Date: 3/05/2023 1:49:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EndUser](
	[enduser_id] [int] IDENTITY(1,1) NOT NULL,
	[email] [varchar](100) NULL,
	[password_hash] [char](128) NULL,
	[dob] [date] NULL,
	[gender] [varchar](1) NULL,
	[username] [varchar](12) NULL,
PRIMARY KEY CLUSTERED 
(
	[enduser_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProfilePicture]    Script Date: 3/05/2023 1:49:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProfilePicture](
	[enduser_id] [int] NOT NULL,
	[picture] [varbinary](max) NULL,
 CONSTRAINT [PK_ProfilePicture] PRIMARY KEY CLUSTERED 
(
	[enduser_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[triggers]    Script Date: 3/05/2023 1:49:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[triggers](
	[trigger_id] [int] IDENTITY(1,1) NOT NULL,
	[trigger_name] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[trigger_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[user_comforts]    Script Date: 3/05/2023 1:49:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[user_comforts](
	[enduser_id] [int] NOT NULL,
	[trigger_id] [int] NOT NULL,
	[entry_date] [date] NOT NULL,
 CONSTRAINT [pk_user_comforts] PRIMARY KEY CLUSTERED 
(
	[enduser_id] ASC,
	[trigger_id] ASC,
	[entry_date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[user_entries]    Script Date: 3/05/2023 1:49:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[user_entries](
	[enduser_id] [int] NOT NULL,
	[entry_date] [date] NOT NULL,
	[content] [varchar](max) NULL,
 CONSTRAINT [pk_entry] PRIMARY KEY CLUSTERED 
(
	[entry_date] ASC,
	[enduser_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[user_score]    Script Date: 3/05/2023 1:49:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[user_score](
	[enduser_id] [int] NOT NULL,
	[entry_date] [date] NOT NULL,
	[score] [real] NULL,
 CONSTRAINT [pk_score] PRIMARY KEY CLUSTERED 
(
	[entry_date] ASC,
	[enduser_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[user_triggers]    Script Date: 3/05/2023 1:49:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[user_triggers](
	[enduser_id] [int] NOT NULL,
	[trigger_id] [int] NOT NULL,
	[entry_date] [date] NOT NULL,
 CONSTRAINT [pk_user_triggers] PRIMARY KEY CLUSTERED 
(
	[enduser_id] ASC,
	[trigger_id] ASC,
	[entry_date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ProfilePicture]  WITH CHECK ADD FOREIGN KEY([enduser_id])
REFERENCES [dbo].[EndUser] ([enduser_id])
GO
ALTER TABLE [dbo].[user_comforts]  WITH CHECK ADD FOREIGN KEY([enduser_id])
REFERENCES [dbo].[EndUser] ([enduser_id])
GO
ALTER TABLE [dbo].[user_comforts]  WITH CHECK ADD FOREIGN KEY([trigger_id])
REFERENCES [dbo].[comforts] ([trigger_id])
GO
ALTER TABLE [dbo].[user_entries]  WITH CHECK ADD FOREIGN KEY([enduser_id])
REFERENCES [dbo].[EndUser] ([enduser_id])
GO
ALTER TABLE [dbo].[user_score]  WITH CHECK ADD FOREIGN KEY([enduser_id])
REFERENCES [dbo].[EndUser] ([enduser_id])
GO
ALTER TABLE [dbo].[user_triggers]  WITH CHECK ADD FOREIGN KEY([enduser_id])
REFERENCES [dbo].[EndUser] ([enduser_id])
GO
ALTER TABLE [dbo].[user_triggers]  WITH CHECK ADD FOREIGN KEY([trigger_id])
REFERENCES [dbo].[triggers] ([trigger_id])
GO
USE [master]
GO
ALTER DATABASE [Lunar] SET  READ_WRITE 
GO
